### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by mas393** [J-Raymer/printlink3d#4]
This issue is for tracking generic project setup tasks. Many of the documentation tasks are outlined in [this doc](https://docs.google.com/document/d/1xppHNvDtQkChSqaZQI7FCG5J9GSH-iyi/edit)

## Todo
- [x] #9
- [x] Create a list of features, posted to an issue, according to specification in [milestone 1 description](https://github.com/margaretstorey/startup2024/blob/master/milestone%201%20-%20proof%20of%20concept.md)
- [x] Create github issue tickets for each feature and link to anticipated completion milestone
- [x] Transfer plaintext knowledge to the github wiki (e.g. contribution doc & Milestone 1 docs folder) 
- [x] #18
- [x] #19

**Comment by mas393** [comment]
I opened a feature list ticket #5. My idea is that we create individual issue tickets for each major feature and link these tickets back to the feature list. Requirement generation and ticket progress would then be tracked separately in each issue ticket.

We will likely have to adjust formatting or content to better suit our future workflow.

**Comment by Jasper-Nelligan** [comment]
Finished moving milestone 1 and contribution docs to the GitHub wiki

**Comment by mas393** [comment]
I created issue tickets for the milestone 1 features with brief descriptions. We can fill out the requirements when we meet.

Issues for features that are scheduled for milestone 2 & 3 will be created later.

**Comment by Jasper-Nelligan** [comment]
Closing this issue as all subtasks are completed
